name: Hardhat Tests

on:
  pull_request:
    branches:
    - main

env:
  INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
  ACCOUNT_PRIVATE_KEY: ${{secrets.ACCOUNT_PRIVATE_KEY}}
  ETHERSCAN_KEY: ${{secrets.ETHERSCAN_KEY}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9'

      - name: Install dependencies
        run: npm run backend:install

      - name: Run Hardhat tests
        run: npm run backend:coverage
