name: Hardhat Tests

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9'

      - name: Install dependencies
        run: npm run backend:install

      - name: Run Hardhat tests
        run: npm run backend:test
